name: top_notch_bottom_bar
description: A beautiful and animated bottom navigation bar. also you are free to customize it way you want.
version: 0.0.1
homepage: https://github.com/sonal-sithara/top_notch_bottom_bar

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
